apiVersion: skaffold/v1beta6
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.VERSION}}"
  artifacts:
  - image: docker.io/jenkinsxio/builder-baseimage
    context: .
    docker:
      dockerfile: Dockerfile
  - image: docker.io/jenkinsxio/builder-ruby-baseimage
    context: .
    docker:
      dockerfile: Dockerfile.ruby
  - image: docker.io/jenkinsxio/builder-swift-baseimage
    context: .
    docker:
      dockerfile: Dockerfile.swift
  kaniko:
    buildContext:
      gcsBucket: jenkinsx-dev-skaffold-kaniko
    pullSecretName: kaniko-secret
    namespace: jx
    timeout: 30m
#    cache:
#     repo: jenkins-x-docker-registry.jx.svc.cluster.local:5000/builder/cache
    dockerConfig:
      secretName: jenkins-docker-cfg
#    flags:
#    - --cache-dir=/workspace
deploy:
  kubectl:
    manifests:
